import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Nav } from "../components/ui/nav.jsx";
// import NextAuthSessionProvider from "@/components/providers/session-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`mx-auto ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <NextAuthSessionProvider> */}
        <Nav />
        {children}
        {/* </NextAuthSessionProvider> */}
      </body>
    </html>
  );
}
